var druid = [
{"spell_level": 0, "name": "Druidcraft"},
{"spell_level": 0, "name": "Guidance"},
{"spell_level": 0, "name": "Mending"},
{"spell_level": 0, "name": "Poison Spray"},
{"spell_level": 0, "name": "Produce Flame"},
{"spell_level": 0, "name": "Resistance"},
{"spell_level": 0, "name": "Shillelagh"},
{"spell_level": 0, "name": "Thorn Whip"},
{"spell_level": 1, "name": "Animal Friendship"},
{"spell_level": 1, "name": "Charm Person"},
{"spell_level": 1, "name": "Create or Destroy Water"},
{"spell_level": 1, "name": "Cure Wounds"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Detect Poison and Disease"},
{"spell_level": 1, "name": "Entangle"},
{"spell_level": 1, "name": "Faerie Fire"},
{"spell_level": 1, "name": "Fog Cloud"},
{"spell_level": 1, "name": "Goodberry"},
{"spell_level": 1, "name": "Healing Word"},
{"spell_level": 1, "name": "Jump"},
{"spell_level": 1, "name": "Longstrider"},
{"spell_level": 1, "name": "Purify Food and Drink"},
{"spell_level": 1, "name": "Speak with Animals"},
{"spell_level": 1, "name": "Thunderwave"},
{"spell_level": 2, "name": "Animal Messenger"},
{"spell_level": 2, "name": "Barkskin"},
{"spell_level": 2, "name": "Beast Sense"},
{"spell_level": 2, "name": "Darkvision"},
{"spell_level": 2, "name": "Enhance Ability"},
{"spell_level": 2, "name": "Find Traps"},
{"spell_level": 2, "name": "Flame Blade"},
{"spell_level": 2, "name": "Flaming Sphere"},
{"spell_level": 2, "name": "Gust of Wind"},
{"spell_level": 2, "name": "Heat Metal"},
{"spell_level": 2, "name": "Hold Person"},
{"spell_level": 2, "name": "Lesser Restoration"},
{"spell_level": 2, "name": "Locate Animals or Plants"},
{"spell_level": 2, "name": "Locate Object"},
{"spell_level": 2, "name": "Moonbeam"},
{"spell_level": 2, "name": "Pass without Trace"},
{"spell_level": 2, "name": "Protection from Poison"},
{"spell_level": 2, "name": "Spike Growth"},
{"spell_level": 3, "name": "Call Lightning"},
{"spell_level": 3, "name": "Conjure Animals"},
{"spell_level": 3, "name": "Daylight"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Feign Death"},
{"spell_level": 3, "name": "Meld into Stone"},
{"spell_level": 3, "name": "Plant Growth"},
{"spell_level": 3, "name": "Protection from Energy"},
{"spell_level": 3, "name": "Sleet Storm"},
{"spell_level": 3, "name": "Speak with Plants"},
{"spell_level": 3, "name": "Water Breathing"},
{"spell_level": 3, "name": "Water Walk"},
{"spell_level": 3, "name": "Wind Wall"},
{"spell_level": 4, "name": "Blight"},
{"spell_level": 4, "name": "Confusion"},
{"spell_level": 4, "name": "Conjure Minor Elementals"},
{"spell_level": 4, "name": "Conjure Woodland Beings"},
{"spell_level": 4, "name": "Control Water"},
{"spell_level": 4, "name": "Dominate Beast"},
{"spell_level": 4, "name": "Freedom of Movement"},
{"spell_level": 4, "name": "Giant Insect"},
{"spell_level": 4, "name": "Grasping Vine"},
{"spell_level": 4, "name": "Hallucinatory Terrain"},
{"spell_level": 4, "name": "Ice Storm"},
{"spell_level": 4, "name": "Locate Creature"},
{"spell_level": 4, "name": "Polymorph"},
{"spell_level": 4, "name": "Stone Shape"},
{"spell_level": 4, "name": "Stoneskin"},
{"spell_level": 4, "name": "Wall of Fire"},
{"spell_level": 5, "name": "Antilife Shell"},
{"spell_level": 5, "name": "Awaken"},
{"spell_level": 5, "name": "Commune with Nature"},
{"spell_level": 5, "name": "Conjure Elemental"},
{"spell_level": 5, "name": "Contagion"},
{"spell_level": 5, "name": "Geas"},
{"spell_level": 5, "name": "Greater Restoration"},
{"spell_level": 5, "name": "Insect Plague"},
{"spell_level": 5, "name": "Mass Cure Wounds"},
{"spell_level": 5, "name": "Planar Binding"},
{"spell_level": 5, "name": "Reincarnate"},
{"spell_level": 5, "name": "Scrying"},
{"spell_level": 5, "name": "Tree Stride"},
{"spell_level": 5, "name": "Wall of Stone"},
{"spell_level": 6, "name": "Conjure Fey"},
{"spell_level": 6, "name": "Find the Path"},
{"spell_level": 6, "name": "Heal"},
{"spell_level": 6, "name": "Heroes’ Feast"},
{"spell_level": 6, "name": "Move Earth"},
{"spell_level": 6, "name": "Sunbeam"},
{"spell_level": 6, "name": "Transport via Plants"},
{"spell_level": 6, "name": "Wall o f Thorns"},
{"spell_level": 6, "name": "Wind Walk"},
{"spell_level": 7, "name": "Fire Storm"},
{"spell_level": 7, "name": "Mirage Arcane"},
{"spell_level": 7, "name": "Plane Shift"},
{"spell_level": 7, "name": "Regenerate"},
{"spell_level": 7, "name": "Reverse Gravity"},
{"spell_level": 8, "name": "Animal Shapes"},
{"spell_level": 8, "name": "Antipathy/Sympathy"},
{"spell_level": 8, "name": "Control Weather"},
{"spell_level": 8, "name": "Earthquake"},
{"spell_level": 8, "name": "Feeblemind"},
{"spell_level": 8, "name": "Sunburst"},
{"spell_level": 8, "name": "Tsunami"},
{"spell_level": 9, "name": "Foresight"},
{"spell_level": 9, "name": "Shapechange"},
{"spell_level": 9, "name": "Storm of Vengeance"},
{"spell_level": 9, "name": "True Resurrection"}];

var bard =
[{"classId": "Bard"},
{"spell_level": 0, "name": "Blade Ward"},
{"spell_level": 0, "name": "Dancing Lights"},
{"spell_level": 0, "name": "Friends"},
{"spell_level": 0, "name": "Light"},
{"spell_level": 0, "name": "Mage Hand"},
{"spell_level": 0, "name": "Mending"},
{"spell_level": 0, "name": "Message"},
{"spell_level": 0, "name": "Minor Illusion"},
{"spell_level": 0, "name": "Prestidigitation"},
{"spell_level": 0, "name": "True Strike"},
{"spell_level": 0, "name": "Vicious Mockery"},
{"spell_level": 1, "name": "Animal Friendship"},
{"spell_level": 1, "name": "Bane"},
{"spell_level": 1, "name": "Charm Person"},
{"spell_level": 1, "name": "Comprehend Languages"},
{"spell_level": 1, "name": "Cure Wounds"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Disguise Self"},
{"spell_level": 1, "name": "Dissonant Whispers"},
{"spell_level": 1, "name": "Faerie Fire"},
{"spell_level": 1, "name": "Feather Fall"},
{"spell_level": 1, "name": "Healing Word"},
{"spell_level": 1, "name": "Heroism"},
{"spell_level": 1, "name": "Identify"},
{"spell_level": 1, "name": "Illusory Script"},
{"spell_level": 1, "name": "Longstrider"},
{"spell_level": 1, "name": "Silent Image"},
{"spell_level": 1, "name": "Sleep"},
{"spell_level": 1, "name": "Speak with Animals"},
{"spell_level": 1, "name": "Tasha’s Hideous Laughter"},
{"spell_level": 1, "name": "Thunderwave"},
{"spell_level": 1, "name": "Unseen Servant"},
{"spell_level": 2, "name": "Animal Messenger"},
{"spell_level": 2, "name": "Blindness/Deafness"},
{"spell_level": 2, "name": "Calm Emotions"},
{"spell_level": 2, "name": "Cloud of Daggers"},
{"spell_level": 2, "name": "Crown of Madness"},
{"spell_level": 2, "name": "Detect Thoughts"},
{"spell_level": 2, "name": "Enhance Ability"},
{"spell_level": 2, "name": "Enthrall"},
{"spell_level": 2, "name": "Heat Metal"},
{"spell_level": 2, "name": "Hold Person"},
{"spell_level": 2, "name": "Invisibility"},
{"spell_level": 2, "name": "Knock"},
{"spell_level": 2, "name": "Lesser Restoration"},
{"spell_level": 2, "name": "Locate Animals or Plants"},
{"spell_level": 2, "name": "Locate Object"},
{"spell_level": 2, "name": "Magic Mouth"},
{"spell_level": 2, "name": "Phantasmal Force"},
{"spell_level": 2, "name": "See Invisibility"},
{"spell_level": 2, "name": "Shatter"},
{"spell_level": 2, "name": "Silence"},
{"spell_level": 2, "name": "Suggestion"},
{"spell_level": 2, "name": "Zone o f Truth"},
{"spell_level": 3, "name": "Bestow Curse"},
{"spell_level": 3, "name": "Clairvoyance"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Fear"},
{"spell_level": 3, "name": "Feign Death"},
{"spell_level": 3, "name": "Glyph o f Warding"},
{"spell_level": 3, "name": "Hypnotic Pattern"},
{"spell_level": 3, "name": "Leomund’s Tiny Hut"},
{"spell_level": 3, "name": "Major Image"},
{"spell_level": 3, "name": "Nondetection"},
{"spell_level": 3, "name": "Plant Growth"},
{"spell_level": 3, "name": "Sending"},
{"spell_level": 3, "name": "Speak with Dead"},
{"spell_level": 3, "name": "Speak with Plants"},
{"spell_level": 3, "name": "Stinking Cloud"},
{"spell_level": 3, "name": "Tongues"},
{"spell_level": 4, "name": "Compulsion"},
{"spell_level": 4, "name": "Confusion"},
{"spell_level": 4, "name": "Dimension Door"},
{"spell_level": 4, "name": "Freedom of Movement"},
{"spell_level": 4, "name": "Greater Invisibility"},
{"spell_level": 4, "name": "Hallucinatory Terrain"},
{"spell_level": 4, "name": "Locate Creature"},
{"spell_level": 4, "name": "Polymorph"},
{"spell_level": 5, "name": "Animate Objects"},
{"spell_level": 5, "name": "Awaken"},
{"spell_level": 5, "name": "Dominate Person"},
{"spell_level": 5, "name": "Dream"},
{"spell_level": 5, "name": "Geas"},
{"spell_level": 5, "name": "Greater Restoration"},
{"spell_level": 5, "name": "Hold Monster"},
{"spell_level": 5, "name": "Legend Lore"},
{"spell_level": 5, "name": "Mass Cure Wounds"},
{"spell_level": 5, "name": "Mislead"},
{"spell_level": 5, "name": "Modify Memory"},
{"spell_level": 5, "name": "Planar Binding"},
{"spell_level": 5, "name": "Raise Dead"},
{"spell_level": 5, "name": "Scrying"},
{"spell_level": 5, "name": "Seeming"},
{"spell_level": 5, "name": "Teleportation Circle"},
{"spell_level": 6, "name": "Eyebite"},
{"spell_level": 6, "name": "Find the Path"},
{"spell_level": 6, "name": "Guards and Wards"},
{"spell_level": 6, "name": "Mass Suggestion"},
{"spell_level": 6, "name": "Otto’s Irresistible Dance"},
{"spell_level": 6, "name": "Programmed Illusion"},
{"spell_level": 6, "name": "True Seeing"},
{"spell_level": 7, "name": "Etherealness"},
{"spell_level": 7, "name": "Forcecage"},
{"spell_level": 7, "name": "Mirage Arcane"},
{"spell_level": 7, "name": "Mordenkainen’s"},
{"spell_level": 7, "name": "Magnificent Mansion"},
{"spell_level": 7, "name": "Mordenkainen’s Sword"},
{"spell_level": 7, "name": "Project Image"},
{"spell_level": 7, "name": "Regenerate"},
{"spell_level": 7, "name": "Resurrection"},
{"spell_level": 7, "name": "Symbol"},
{"spell_level": 7, "name": "Teleport"},
{"spell_level": 8, "name": "Dominate Monster"},
{"spell_level": 8, "name": "Feeblemind"},
{"spell_level": 8, "name": "Glibness"},
{"spell_level": 8, "name": "Mind Blank"},
{"spell_level": 8, "name": "Power Word Stun"},
{"spell_level": 9, "name": "Foresight"},
{"spell_level": 9, "name": "Power Word Heal"},
{"spell_level": 9, "name": "Power Word Kill"},
{"spell_level": 9, "name": "True Polymorph"}];


var cleric = 
[{"classId": "Cleric"},
{"spell_level": 0, "name": "Guidance"},
{"spell_level": 0, "name": "Light"},
{"spell_level": 0, "name": "Mending"},
{"spell_level": 0, "name": "Resistance"},
{"spell_level": 0, "name": "Sacred Flame"},
{"spell_level": 0, "name": "Spare the Dying"},
{"spell_level": 0, "name": "Thaumaturgy"},
{"spell_level": 1, "name": "Bane"},
{"spell_level": 1, "name": "Bless"},
{"spell_level": 1, "name": "Command"},
{"spell_level": 1, "name": "Create or Destroy Water"},
{"spell_level": 1, "name": "Cure Wounds"},
{"spell_level": 1, "name": "Detect Evil and Good"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Detect Poison and Disease"},
{"spell_level": 1, "name": "Guiding Bolt"},
{"spell_level": 1, "name": "Healing Word"},
{"spell_level": 1, "name": "Inflict Wounds"},
{"spell_level": 1, "name": "Protection from"},
{"spell_level": 1, "name": "Evil and Good"},
{"spell_level": 1, "name": "Purify Food and Drink"},
{"spell_level": 1, "name": "Sanctuary"},
{"spell_level": 1, "name": "Shield of Faith"},
{"spell_level": 2, "name": "Aid"},
{"spell_level": 2, "name": "Augury"},
{"spell_level": 2, "name": "Blindness/Deafness"},
{"spell_level": 2, "name": "Calm Emotions"},
{"spell_level": 2, "name": "Continual Flame"},
{"spell_level": 2, "name": "Enhance Ability"},
{"spell_level": 2, "name": "Find Traps"},
{"spell_level": 2, "name": "Gentle Repose"},
{"spell_level": 2, "name": "Hold Person"},
{"spell_level": 2, "name": "Lesser Restoration"},
{"spell_level": 2, "name": "Locate Object"},
{"spell_level": 2, "name": "Prayer of Healing"},
{"spell_level": 2, "name": "Protection from Poison"},
{"spell_level": 2, "name": "Silence"},
{"spell_level": 2, "name": "Spiritual Weapon"},
{"spell_level": 2, "name": "Warding Bond"},
{"spell_level": 2, "name": "Zone of Truth"},
{"spell_level": 3, "name": "Animate Dead"},
{"spell_level": 3, "name": "Beacon of Hope"},
{"spell_level": 3, "name": "Bestow Curse"},
{"spell_level": 3, "name": "Clairvoyance"},
{"spell_level": 3, "name": "Create Food and Water"},
{"spell_level": 3, "name": "Daylight"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Feign Death"},
{"spell_level": 3, "name": "Glyph of Warding"},
{"spell_level": 3, "name": "Magic Circle"},
{"spell_level": 3, "name": "Mass Healing Word"},
{"spell_level": 3, "name": "Meld into Stone"},
{"spell_level": 3, "name": "Protection from Energy"},
{"spell_level": 3, "name": "Remove Curse"},
{"spell_level": 3, "name": "Revivify"},
{"spell_level": 3, "name": "Sending"},
{"spell_level": 3, "name": "Speak with Dead"},
{"spell_level": 3, "name": "Spirit Guardians"},
{"spell_level": 3, "name": "Tongues"},
{"spell_level": 3, "name": "Water Walk"},
{"spell_level": 4, "name": "Banishment"},
{"spell_level": 4, "name": "Control Water"},
{"spell_level": 4, "name": "Death Ward"},
{"spell_level": 4, "name": "Divination"},
{"spell_level": 4, "name": "Freedom of Movement"},
{"spell_level": 4, "name": "Guardian of Faith"},
{"spell_level": 4, "name": "Locate Creature"},
{"spell_level": 4, "name": "Stone Shape"},
{"spell_level": 5, "name": "Commune"},
{"spell_level": 5, "name": "Contagion"},
{"spell_level": 5, "name": "Dispel Evil and Good"},
{"spell_level": 5, "name": "Flame Strike"},
{"spell_level": 5, "name": "Geas"},
{"spell_level": 5, "name": "Greater Restoration"},
{"spell_level": 5, "name": "Hallow"},
{"spell_level": 5, "name": "Insect Plague"},
{"spell_level": 5, "name": "Legend Lore"},
{"spell_level": 5, "name": "Mass Cure Wounds"},
{"spell_level": 5, "name": "Planar Binding"},
{"spell_level": 5, "name": "Raise Dead"},
{"spell_level": 5, "name": "Scrying"},
{"spell_level": 6, "name": "Blade Barrier"},
{"spell_level": 6, "name": "Create Undead"},
{"spell_level": 6, "name": "Find the Path"},
{"spell_level": 6, "name": "Forbiddance"},
{"spell_level": 6, "name": "Harm"},
{"spell_level": 6, "name": "Heal"},
{"spell_level": 6, "name": "Heroes’ Feast"},
{"spell_level": 6, "name": "Planar Ally"},
{"spell_level": 6, "name": "True Seeing"},
{"spell_level": 6, "name": "Word of Recall"},
{"spell_level": 7, "name": "Conjure Celestial"},
{"spell_level": 7, "name": "Divine Word"},
{"spell_level": 7, "name": "Etherealness"},
{"spell_level": 7, "name": "Fire Storm"},
{"spell_level": 7, "name": "Plane Shift"},
{"spell_level": 7, "name": "Regenerate"},
{"spell_level": 7, "name": "Resurrection"},
{"spell_level": 7, "name": "Symbol"},
{"spell_level": 8, "name": "Antimagic Field"},
{"spell_level": 8, "name": "Control Weather"},
{"spell_level": 8, "name": "Earthquake"},
{"spell_level": 8, "name": "Holy Aura"},
{"spell_level": 9, "name": "Astral Projection"},
{"spell_level": 9, "name": "Gate"},
{"spell_level": 9, "name": "Mass Heal"},
{"spell_level": 9, "name": "True Resurrection"}];

var paladin =
[{"classId": "Paladin"},
{"spell_level": 1, "name": "Bless"},
{"spell_level": 1, "name": "Command"},
{"spell_level": 1, "name": "Compelled Duel"},
{"spell_level": 1, "name": "Cure Wounds"},
{"spell_level": 1, "name": "Detect Evil and Good"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Detect Poison and Disease"},
{"spell_level": 1, "name": "Divine Favor"},
{"spell_level": 1, "name": "Heroism"},
{"spell_level": 1, "name": "Protection from"},
{"spell_level": 1, "name": "Evil and Good"},
{"spell_level": 1, "name": "Purify Food and Drink"},
{"spell_level": 1, "name": "Searing Smite"},
{"spell_level": 1, "name": "Shield of Faith"},
{"spell_level": 1, "name": "Thunderous Smite"},
{"spell_level": 1, "name": "Wrathful Smite"},
{"spell_level": 2, "name": "Aid"},
{"spell_level": 2, "name": "Branding Smite"},
{"spell_level": 2, "name": "Find Steed"},
{"spell_level": 2, "name": "Lesser Restoration"},
{"spell_level": 2, "name": "Locate Object"},
{"spell_level": 2, "name": "Magic Weapon"},
{"spell_level": 2, "name": "Protection from Poison"},
{"spell_level": 2, "name": "Zone o f Truth"},
{"spell_level": 3, "name": "Aura of Vitality"},
{"spell_level": 3, "name": "Blinding Smite"},
{"spell_level": 3, "name": "Create Food and Water"},
{"spell_level": 3, "name": "Crusader's Mantle"},
{"spell_level": 3, "name": "Daylight"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Elemental Weapon"},
{"spell_level": 3, "name": "Magic Circle"},
{"spell_level": 3, "name": "Remove Curse"},
{"spell_level": 3, "name": "Revivify"},
{"spell_level": 4, "name": "Aura of Life"},
{"spell_level": 4, "name": "Aura of Purity"},
{"spell_level": 4, "name": "Banishment"},
{"spell_level": 4, "name": "Death Ward"},
{"spell_level": 4, "name": "Locate Creature"},
{"spell_level": 4, "name": "Staggering Smite"},
{"spell_level": 5, "name": "Banishing Smite"},
{"spell_level": 5, "name": "Circle of Power"},
{"spell_level": 5, "name": "Destructive Smite"},
{"spell_level": 5, "name": "Dispel Evil and Good"},
{"spell_level": 5, "name": "Geas"},
{"spell_level": 5, "name": "Raise Dead"}];


var ranger = 
[{"classId": "Ranger"},
{"spell_level": 1, "name": "Alarm"},
{"spell_level": 1, "name": "Animal Friendship"},
{"spell_level": 1, "name": "Cure Wounds"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Detect Poison and Disease"},
{"spell_level": 1, "name": "Ensnaring Strike"},
{"spell_level": 1, "name": "Fog Cloud"},
{"spell_level": 1, "name": "Goodberry"},
{"spell_level": 1, "name": "Hail o f Thorns"},
{"spell_level": 1, "name": "Hunter’s Mark"},
{"spell_level": 1, "name": "Jump"},
{"spell_level": 1, "name": "Longstrider"},
{"spell_level": 1, "name": "Speak with Animals"},
{"spell_level": 2, "name": "Animal Messenger"},
{"spell_level": 2, "name": "Barkskin"},
{"spell_level": 2, "name": "Beast Sense"},
{"spell_level": 2, "name": "Cordon of Arrows"},
{"spell_level": 2, "name": "Darkvision"},
{"spell_level": 2, "name": "Find Traps"},
{"spell_level": 2, "name": "Lesser Restoration"},
{"spell_level": 2, "name": "Locate Animals or Plants"},
{"spell_level": 2, "name": "Locate Object"},
{"spell_level": 2, "name": "Pass without Trace"},
{"spell_level": 2, "name": "Protection from Poison"},
{"spell_level": 2, "name": "Silence"},
{"spell_level": 2, "name": "Spike Growth"},
{"spell_level": 3, "name": "Conjure Animals"},
{"spell_level": 3, "name": "Conjure Barrage"},
{"spell_level": 3, "name": "Daylight"},
{"spell_level": 3, "name": "Lightning Arrow"},
{"spell_level": 3, "name": "Nondetection"},
{"spell_level": 3, "name": "Plant Growth"},
{"spell_level": 3, "name": "Protection from Energy"},
{"spell_level": 3, "name": "Speak with Plants"},
{"spell_level": 3, "name": "Water Breathing"},
{"spell_level": 3, "name": "Water Walk"},
{"spell_level": 3, "name": "Wind Wall"},
{"spell_level": 4, "name": "Conjure Woodland Beings"},
{"spell_level": 4, "name": "Freedom of Movement"},
{"spell_level": 4, "name": "Grasping Vine"},
{"spell_level": 4, "name": "Locate Creature"},
{"spell_level": 4, "name": "Stoneskin"},
{"spell_level": 5, "name": "Commune with Nature"},
{"spell_level": 5, "name": "Conjure Volley"},
{"spell_level": 5, "name": "Swift Quiver"},
{"spell_level": 5, "name": "Tree Stride"}];


var sorcerer = 
[{"classId": "Sorcerer"},
{"spell_level": 0, "name": "Acid Splash"},
{"spell_level": 0, "name": "Blade Ward"},
{"spell_level": 0, "name": "Chill Touch"},
{"spell_level": 0, "name": "Dancing Lights"},
{"spell_level": 0, "name": "Fire Bolt"},
{"spell_level": 0, "name": "Friends"},
{"spell_level": 0, "name": "Light"},
{"spell_level": 0, "name": "Mage Hand"},
{"spell_level": 0, "name": "Mending"},
{"spell_level": 0, "name": "Message"},
{"spell_level": 0, "name": "Minor Illusion"},
{"spell_level": 0, "name": "Poison Spray"},
{"spell_level": 0, "name": "Prestidigitation"},
{"spell_level": 0, "name": "Ray of Frost"},
{"spell_level": 0, "name": "Shocking Grasp"},
{"spell_level": 0, "name": "True Strike"},
{"spell_level": 1, "name": "Burning Hands"},
{"spell_level": 1, "name": "Charm Person"},
{"spell_level": 1, "name": "Chromatic Orb"},
{"spell_level": 1, "name": "Color Spray"},
{"spell_level": 1, "name": "Comprehend Languages"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Disguise Self"},
{"spell_level": 1, "name": "Expeditious Retreat"},
{"spell_level": 1, "name": "False Life"},
{"spell_level": 1, "name": "Feather Fall"},
{"spell_level": 1, "name": "Fog Cloud"},
{"spell_level": 1, "name": "Jump"},
{"spell_level": 1, "name": "Mage Armor"},
{"spell_level": 1, "name": "Magic Missile"},
{"spell_level": 1, "name": "Ray of Sickness"},
{"spell_level": 1, "name": "Shield"},
{"spell_level": 1, "name": "Silent Image"},
{"spell_level": 1, "name": "Sleep"},
{"spell_level": 1, "name": "Thunderwave"},
{"spell_level": 1, "name": "Witch Bolt"},
{"spell_level": 2, "name": "Alter Self"},
{"spell_level": 2, "name": "Blindness/Deafness"},
{"spell_level": 2, "name": "Blur"},
{"spell_level": 2, "name": "Cloud of Daggers"},
{"spell_level": 2, "name": "Crown of Madness"},
{"spell_level": 2, "name": "Darkness"},
{"spell_level": 2, "name": "Darkvision"},
{"spell_level": 2, "name": "Detect Thoughts"},
{"spell_level": 2, "name": "Enhance Ability"},
{"spell_level": 2, "name": "Enlarge/Reduce"},
{"spell_level": 2, "name": "Gust of Wind"},
{"spell_level": 2, "name": "Hold Person"},
{"spell_level": 2, "name": "Invisibility"},
{"spell_level": 2, "name": "Knock"},
{"spell_level": 2, "name": "Levitate"},
{"spell_level": 2, "name": "Mirror Image"},
{"spell_level": 2, "name": "Misty Step"},
{"spell_level": 2, "name": "Phantasmal Force"},
{"spell_level": 2, "name": "Scorching Ray"},
{"spell_level": 2, "name": "See Invisibility"},
{"spell_level": 2, "name": "Shatter"},
{"spell_level": 2, "name": "Spider Climb"},
{"spell_level": 2, "name": "Suggestion"},
{"spell_level": 2, "name": "Web"},
{"spell_level": 3, "name": "Blink"},
{"spell_level": 3, "name": "Clairvoyance"},
{"spell_level": 3, "name": "Counterspell"},
{"spell_level": 3, "name": "Daylight"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Fear"},
{"spell_level": 3, "name": "Fireball"},
{"spell_level": 3, "name": "Fly"},
{"spell_level": 3, "name": "Gaseous Form"},
{"spell_level": 3, "name": "Haste"},
{"spell_level": 3, "name": "Hypnotic Pattern"},
{"spell_level": 3, "name": "Lightning Bolt"},
{"spell_level": 3, "name": "Major Image"},
{"spell_level": 3, "name": "Protection from Energy"},
{"spell_level": 3, "name": "Sleet Storm"},
{"spell_level": 3, "name": "Slow"},
{"spell_level": 3, "name": "Stinking Cloud"},
{"spell_level": 3, "name": "Tongues"},
{"spell_level": 3, "name": "Water Breathing"},
{"spell_level": 3, "name": "Water Walk"},
{"spell_level": 4, "name": "Banishment"},
{"spell_level": 4, "name": "Blight"},
{"spell_level": 4, "name": "Confusion"},
{"spell_level": 4, "name": "Dimension Door"},
{"spell_level": 4, "name": "Dominate Beast"},
{"spell_level": 4, "name": "Greater Invisibility"},
{"spell_level": 4, "name": "Ice Storm"},
{"spell_level": 4, "name": "Polymorph"},
{"spell_level": 4, "name": "Stoneskin"},
{"spell_level": 4, "name": "Wall of Fire"},
{"spell_level": 5, "name": "Animate Objects"},
{"spell_level": 5, "name": "Cloudkill"},
{"spell_level": 5, "name": "Cone of Cold"},
{"spell_level": 5, "name": "Creation"},
{"spell_level": 5, "name": "Dominate Person"},
{"spell_level": 5, "name": "Hold Monster"},
{"spell_level": 5, "name": "Insect Plague"},
{"spell_level": 5, "name": "Seeming"},
{"spell_level": 5, "name": "Telekinesis"},
{"spell_level": 5, "name": "Teleportation Circle"},
{"spell_level": 5, "name": "Wall of Stone"},
{"spell_level": 6, "name": "Arcane Gate"},
{"spell_level": 6, "name": "Chain Lightning"},
{"spell_level": 6, "name": "Circle of Death"},
{"spell_level": 6, "name": "Disintegrate"},
{"spell_level": 6, "name": "Eyebite"},
{"spell_level": 6, "name": "Globe of Invulnerability"},
{"spell_level": 6, "name": "Mass Suggestion"},
{"spell_level": 6, "name": "Move Earth"},
{"spell_level": 6, "name": "Sunbeam"},
{"spell_level": 6, "name": "True Seeing"},
{"spell_level": 7, "name": "Delayed Blast Fireball"},
{"spell_level": 7, "name": "Etherealness"},
{"spell_level": 7, "name": "Finger of Death"},
{"spell_level": 7, "name": "Fire Storm"},
{"spell_level": 7, "name": "Plane Shift"},
{"spell_level": 7, "name": "Prismatic Spray"},
{"spell_level": 7, "name": "Reverse Gravity"},
{"spell_level": 7, "name": "Teleport"},
{"spell_level": 8, "name": "Dominate Monster"},
{"spell_level": 8, "name": "Earthquake"},
{"spell_level": 8, "name": "Incendiary Cloud"},
{"spell_level": 8, "name": "Power Word Stun"},
{"spell_level": 8, "name": "Sunburst"},
{"spell_level": 9, "name": "Gate"},
{"spell_level": 9, "name": "Meteor Swarm"},
{"spell_level": 9, "name": "Power Word Kill"},
{"spell_level": 9, "name": "Time Stop"},
{"spell_level": 9, "name": "Wish"}];


var warlock =
[{"classId": "Warlock"},
{"spell_level": 0, "name": "Blade Ward"},
{"spell_level": 0, "name": "Chill Touch"},
{"spell_level": 0, "name": "Eldritch Blast"},
{"spell_level": 0, "name": "Friends"},
{"spell_level": 0, "name": "Mage Hand"},
{"spell_level": 0, "name": "Minor Illusion"},
{"spell_level": 0, "name": "Poison Spray"},
{"spell_level": 0, "name": "Prestidigitation"},
{"spell_level": 0, "name": "True Strike"},
{"spell_level": 1, "name": "Armor of Agathys"},
{"spell_level": 1, "name": "Arms of Hadar"},
{"spell_level": 1, "name": "Charm Person"},
{"spell_level": 1, "name": "Comprehend Languages"},
{"spell_level": 1, "name": "Expeditious Retreat"},
{"spell_level": 1, "name": "Hellish Rebuke"},
{"spell_level": 1, "name": "Hex"},
{"spell_level": 1, "name": "Illusory Script"},
{"spell_level": 1, "name": "Protection from"},
{"spell_level": 1, "name": "Evil and Good"},
{"spell_level": 1, "name": "Unseen Servant"},
{"spell_level": 1, "name": "Witch Bolt"},
{"spell_level": 2, "name": "Cloud of Daggers"},
{"spell_level": 2, "name": "Crown of Madness"},
{"spell_level": 2, "name": "Darkness"},
{"spell_level": 2, "name": "Enthrall"},
{"spell_level": 2, "name": "Hold Person"},
{"spell_level": 2, "name": "Invisibility"},
{"spell_level": 2, "name": "Mirror Image"},
{"spell_level": 2, "name": "Misty Step"},
{"spell_level": 2, "name": "Ray of Enfeeblement"},
{"spell_level": 2, "name": "Shatter"},
{"spell_level": 2, "name": "Spider Climb"},
{"spell_level": 2, "name": "Suggestion"},
{"spell_level": 3, "name": "Counterspell"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Fear"},
{"spell_level": 3, "name": "Fly"},
{"spell_level": 3, "name": "Gaseous Form"},
{"spell_level": 3, "name": "Hunger of Hadar"},
{"spell_level": 3, "name": "Hypnotic Pattern"},
{"spell_level": 3, "name": "Magic Circle"},
{"spell_level": 3, "name": "Major Image"},
{"spell_level": 3, "name": "Remove Curse"},
{"spell_level": 3, "name": "Tongues"},
{"spell_level": 3, "name": "Vampiric Touch"},
{"spell_level": 4, "name": "Banishment"},
{"spell_level": 4, "name": "Blight"},
{"spell_level": 4, "name": "Dimension Door"},
{"spell_level": 4, "name": "Hallucinatory Terrain"},
{"spell_level": 5, "name": "Contact Other Plane"},
{"spell_level": 5, "name": "Dream"},
{"spell_level": 5, "name": "Hold Monster"},
{"spell_level": 5, "name": "Scrying"},
{"spell_level": 6, "name": "Arcane Gate"},
{"spell_level": 6, "name": "Circle of Death"},
{"spell_level": 6, "name": "Conjure Fey"},
{"spell_level": 6, "name": "Create Undead"},
{"spell_level": 6, "name": "Eyebite"},
{"spell_level": 6, "name": "Flesh to Stone"},
{"spell_level": 6, "name": "Mass Suggestion"},
{"spell_level": 6, "name": "True Seeing"},
{"spell_level": 7, "name": "Etherealness"},
{"spell_level": 7, "name": "Finger of Death"},
{"spell_level": 7, "name": "Forcecage"},
{"spell_level": 7, "name": "Plane Shift"},
{"spell_level": 8, "name": "Demiplane"},
{"spell_level": 8, "name": "Dominate Monster"},
{"spell_level": 8, "name": "Feeblemind"},
{"spell_level": 8, "name": "Glibness"},
{"spell_level": 8, "name": "Power Word Stun"},
{"spell_level": 9, "name": "Astral Projection"},
{"spell_level": 9, "name": "Foresight"},
{"spell_level": 9, "name": "Imprisonment"},
{"spell_level": 9, "name": "Power Word Kill"},
{"spell_level": 9, "name": "True Polymorph"}];


var wizard =
[{"classId": "Wizard"},
{"spell_level": 0, "name": "Acid Splash"},
{"spell_level": 0, "name": "Blade Ward"},
{"spell_level": 0, "name": "Chill Touch"},
{"spell_level": 0, "name": "Dancing Lights"},
{"spell_level": 0, "name": "Fire Bolt"},
{"spell_level": 0, "name": "Friends"},
{"spell_level": 0, "name": "Light"},
{"spell_level": 0, "name": "Mage Hand"},
{"spell_level": 0, "name": "Mending"},
{"spell_level": 0, "name": "Message"},
{"spell_level": 0, "name": "Minor Illusion"},
{"spell_level": 0, "name": "Poison Spray"},
{"spell_level": 0, "name": "Prestidigitation"},
{"spell_level": 0, "name": "Ray of Frost"},
{"spell_level": 0, "name": "Shocking Grasp"},
{"spell_level": 0, "name": "True Strike"},
{"spell_level": 1, "name": "Alarm"},
{"spell_level": 1, "name": "Burning Hands"},
{"spell_level": 1, "name": "Charm Person"},
{"spell_level": 1, "name": "Chromatic Orb"},
{"spell_level": 1, "name": "Color Spray"},
{"spell_level": 1, "name": "Comprehend Languages"},
{"spell_level": 1, "name": "Detect Magic"},
{"spell_level": 1, "name": "Disguise Self"},
{"spell_level": 1, "name": "Expeditious Retreat"},
{"spell_level": 1, "name": "False Life"},
{"spell_level": 1, "name": "Feather Fall"},
{"spell_level": 1, "name": "Find Familiar"},
{"spell_level": 1, "name": "Fog Cloud"},
{"spell_level": 1, "name": "Grease"},
{"spell_level": 1, "name": "Identify"},
{"spell_level": 1, "name": "Illusory Script"},
{"spell_level": 1, "name": "Jump"},
{"spell_level": 1, "name": "Longstrider"},
{"spell_level": 1, "name": "Mage Armor"},
{"spell_level": 1, "name": "Magic Missile"},
{"spell_level": 1, "name": "Protection from"},
{"spell_level": 1, "name": "Evil and Good"},
{"spell_level": 1, "name": "Ray of Sickness"},
{"spell_level": 1, "name": "Shield"},
{"spell_level": 1, "name": "Silent Image"},
{"spell_level": 1, "name": "Sleep"},
{"spell_level": 1, "name": "Tasha’s Hideous Laughter"},
{"spell_level": 1, "name": "Tenser’s Floating Disk"},
{"spell_level": 1, "name": "Thunderwave"},
{"spell_level": 1, "name": "Unseen Servant"},
{"spell_level": 1, "name": "Witch Bolt"},
{"spell_level": 2, "name": "Alter Self"},
{"spell_level": 2, "name": "Arcane Lock"},
{"spell_level": 2, "name": "Blindness/Deafness"},
{"spell_level": 2, "name": "Blur"},
{"spell_level": 2, "name": "Cloud of Daggers"},
{"spell_level": 2, "name": "Continual Flame"},
{"spell_level": 2, "name": "Crown of Madness"},
{"spell_level": 2, "name": "Darkness"},
{"spell_level": 2, "name": "Darkvision"},
{"spell_level": 2, "name": "Detect Thoughts"},
{"spell_level": 2, "name": "Enlarge/Reduce"},
{"spell_level": 2, "name": "Flaming Sphere"},
{"spell_level": 2, "name": "Gentle Repose"},
{"spell_level": 2, "name": "Gust of Wind"},
{"spell_level": 2, "name": "Hold Person"},
{"spell_level": 2, "name": "Invisibility"},
{"spell_level": 2, "name": "Knock"},
{"spell_level": 2, "name": "Levitate"},
{"spell_level": 2, "name": "Locate Object"},
{"spell_level": 2, "name": "Magic Mouth"},
{"spell_level": 2, "name": "Magic Weapon"},
{"spell_level": 2, "name": "Melf’s Acid Arrow"},
{"spell_level": 2, "name": "Mirror Image"},
{"spell_level": 2, "name": "Misty Step"},
{"spell_level": 2, "name": "Nystul’s Magic Aura"},
{"spell_level": 2, "name": "Phantasmal Force"},
{"spell_level": 2, "name": "Ray of Enfeeblement"},
{"spell_level": 2, "name": "Rope Trick"},
{"spell_level": 2, "name": "Scorching Ray"},
{"spell_level": 2, "name": "See Invisibility"},
{"spell_level": 2, "name": "Shatter"},
{"spell_level": 2, "name": "Spider Climb"},
{"spell_level": 2, "name": "Suggestion"},
{"spell_level": 2, "name": "Web"},
{"spell_level": 3, "name": "Animate Dead"},
{"spell_level": 3, "name": "Bestow Curse"},
{"spell_level": 3, "name": "Blink"},
{"spell_level": 3, "name": "Clairvoyance"},
{"spell_level": 3, "name": "Counterspell"},
{"spell_level": 3, "name": "Dispel Magic"},
{"spell_level": 3, "name": "Fear"},
{"spell_level": 3, "name": "Feign Death"},
{"spell_level": 3, "name": "Fireball"},
{"spell_level": 3, "name": "Fly"},
{"spell_level": 3, "name": "Gaseous Form"},
{"spell_level": 3, "name": "Glyph o f Warding"},
{"spell_level": 3, "name": "Haste"},
{"spell_level": 3, "name": "Hypnotic Pattern"},
{"spell_level": 3, "name": "Leomund’s Tiny Hut"},
{"spell_level": 3, "name": "Lightning Bolt"},
{"spell_level": 3, "name": "Magic Circle"},
{"spell_level": 3, "name": "Major Image"},
{"spell_level": 3, "name": "Nondetection"},
{"spell_level": 3, "name": "Phantom Steed"},
{"spell_level": 3, "name": "Protection from Energy"},
{"spell_level": 3, "name": "Remove Curse"},
{"spell_level": 3, "name": "Sending"},
{"spell_level": 3, "name": "Sleet Storm"},
{"spell_level": 3, "name": "Slow"},
{"spell_level": 3, "name": "Stinking Cloud"},
{"spell_level": 3, "name": "Tongues"},
{"spell_level": 3, "name": "Vampiric Touch"},
{"spell_level": 3, "name": "Water Breathing"},
{"spell_level": 4, "name": "Arcane Eye"},
{"spell_level": 4, "name": "Banishment"},
{"spell_level": 4, "name": "Blight"},
{"spell_level": 4, "name": "Confusion"},
{"spell_level": 4, "name": "Conjure Minor Elementals"},
{"spell_level": 4, "name": "Control Water"},
{"spell_level": 4, "name": "Dimension Door"},
{"spell_level": 4, "name": "Evard's Black Tentacles"},
{"spell_level": 4, "name": "Fabricate"},
{"spell_level": 4, "name": "Fire Shield"},
{"spell_level": 4, "name": "Greater Invisibility"},
{"spell_level": 4, "name": "Hallucinatory Terrain"},
{"spell_level": 4, "name": "Ice Storm"},
{"spell_level": 4, "name": "Leomund’s Secret Chest"},
{"spell_level": 4, "name": "Locate Creature"},
{"spell_level": 4, "name": "Mordenkainen’s"},
{"spell_level": 4, "name": "Faithful Hound"},
{"spell_level": 4, "name": "Mordenkainen’s"},
{"spell_level": 4, "name": "Private Sanctum"},
{"spell_level": 4, "name": "Otiluke’s Resilient Sphere"},
{"spell_level": 4, "name": "Phantasmal Killer"},
{"spell_level": 4, "name": "Polymorph"},
{"spell_level": 4, "name": "Stone Shape"},
{"spell_level": 4, "name": "Stoneskin"},
{"spell_level": 4, "name": "Wall of Fire"},
{"spell_level": 5, "name": "Animate Objects"},
{"spell_level": 5, "name": "Bigby’s Hand"},
{"spell_level": 5, "name": "CloudkilI"},
{"spell_level": 5, "name": "Cone of Cold"},
{"spell_level": 5, "name": "Conjure Elemental"},
{"spell_level": 5, "name": "Contact Other Plane"},
{"spell_level": 5, "name": "Creation"},
{"spell_level": 5, "name": "Dominate Person"},
{"spell_level": 5, "name": "Dream"},
{"spell_level": 5, "name": "Geas"},
{"spell_level": 5, "name": "Hold Monster"},
{"spell_level": 5, "name": "Legend Lore"},
{"spell_level": 5, "name": "Mislead"},
{"spell_level": 5, "name": "Modify Memory"},
{"spell_level": 5, "name": "Passwall"},
{"spell_level": 5, "name": "Planar Binding"},
{"spell_level": 5, "name": "Rary’s Telepathic Bond"},
{"spell_level": 5, "name": "Scrying"},
{"spell_level": 5, "name": "Seeming"},
{"spell_level": 5, "name": "Telekinesis"},
{"spell_level": 5, "name": "Teleportation Circle"},
{"spell_level": 5, "name": "Wall of Force"},
{"spell_level": 5, "name": "Wall of Stone"},
{"spell_level": 6, "name": "Arcane Gate"},
{"spell_level": 6, "name": "Chain Lightning"},
{"spell_level": 6, "name": "Circle of Death"},
{"spell_level": 6, "name": "Contingency"},
{"spell_level": 6, "name": "Create Undead"},
{"spell_level": 6, "name": "Disintegrate"},
{"spell_level": 6, "name": "Drawmij’s Instant"},
{"spell_level": 6, "name": "Summons"},
{"spell_level": 6, "name": "Eyebite"},
{"spell_level": 6, "name": "Flesh to Stone"},
{"spell_level": 6, "name": "Globe of Invulnerability"},
{"spell_level": 6, "name": "Guards and Wards"},
{"spell_level": 6, "name": "Magic Jar"},
{"spell_level": 6, "name": "Mass Suggestion"},
{"spell_level": 6, "name": "Move Earth"},
{"spell_level": 6, "name": "Otiluke’s Freezing Sphere"},
{"spell_level": 6, "name": "Otto’s Irresistible Dance"},
{"spell_level": 6, "name": "Programmed Illusion"},
{"spell_level": 6, "name": "Sunbeam"},
{"spell_level": 6, "name": "True Seeing"},
{"spell_level": 6, "name": "Wall of Ice"},
{"spell_level": 7, "name": "Delayed Blast Fireball"},
{"spell_level": 7, "name": "Etherealness"},
{"spell_level": 7, "name": "Finger of Death"},
{"spell_level": 7, "name": "Forcecage"},
{"spell_level": 7, "name": "Mirage Arcane"},
{"spell_level": 7, "name": "Mordenkainen's"},
{"spell_level": 7, "name": "Magnificent Mansion"},
{"spell_level": 7, "name": "Mordenkainen’s Sword"},
{"spell_level": 7, "name": "Plane Shift"},
{"spell_level": 7, "name": "Prismatic Spray"},
{"spell_level": 7, "name": "Project Image"},
{"spell_level": 7, "name": "Reverse Gravity"},
{"spell_level": 7, "name": "Sequester"},
{"spell_level": 7, "name": "Simulacrum"},
{"spell_level": 7, "name": "Symbol"},
{"spell_level": 7, "name": "Teleport"},
{"spell_level": 8, "name": "Antimagic Field"},
{"spell_level": 8, "name": "Antipathy/Sympathy"},
{"spell_level": 8, "name": "Clone"},
{"spell_level": 8, "name": "Control Weather"},
{"spell_level": 8, "name": "Demiplane"},
{"spell_level": 8, "name": "Dominate Monster"},
{"spell_level": 8, "name": "Feeblemind"},
{"spell_level": 8, "name": "Incendiary Cloud"},
{"spell_level": 8, "name": "Maze"},
{"spell_level": 8, "name": "Mind Blank"},
{"spell_level": 8, "name": "Power Word Stun"},
{"spell_level": 8, "name": "Sunburst"},
{"spell_level": 8, "name": "Telepathy"},
{"spell_level": 8, "name": "Trap the Soul"},
{"spell_level": 9, "name": "Astral Projection"},
{"spell_level": 9, "name": "Foresight"},
{"spell_level": 9, "name": "Gate"},
{"spell_level": 9, "name": "Imprisonment"},
{"spell_level": 9, "name": "Meteor Swarm"},
{"spell_level": 9, "name": "Power Word Kill"},
{"spell_level": 9, "name": "Prismatic Wall"},
{"spell_level": 9, "name": "Shapechange"},
{"spell_level": 9, "name": "Time Stop"},
{"spell_level": 9, "name": "True Polymorph"},
{"spell_level": 9, "name": "Weird"},
{"spell_level": 9, "name": "Wish"}];

